
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
   # url: jdbc:mysql://123.207.235.243/sell?characterEncoding=utf-8&userSSL=false
    url: jdbc:mysql://192.168.3.102/sell?characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server:


  port: 8080


  context-path: /sell
